CONFIG = config.yaml


inspect:
	containerlab inspect -t $(CONFIG)

deploy:
	containerlab deploy -t $(CONFIG)

destroy:
	containerlab destroy -t $(CONFIG)

graph:
	containerlab graph -t $(CONFIG)

save:
	containerlab save -t $(CONFIG)
